2021-06-18 23:53:42,476 | DEBUG: Here you have some information for debugging.
2021-06-18 23:53:42,510 | DEBUG: Starting new HTTPS connection (1): dev-48491388.okta.com:443
2021-06-18 23:53:43,723 | DEBUG: https://dev-48491388.okta.com:443 "POST /api/v1/groups HTTP/1.1" 400 None
2021-06-18 23:53:43,731 | INFO: {"errorCode":"E0000001","errorSummary":"Api validation failed: name","errorLink":"E0000001","errorId":"oaeYuiMxvy1S_qEzwFXvvT6og","errorCauses":[{"errorSummary":"name: An object with this field already exists in the current organization"}]}
